# Generated by Django 4.0.8 on 2024-10-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subjects_rename_subjects_courseallocation_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='courseallocation',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
