# Generated by Django 4.0.8 on 2024-10-07 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('condition', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('notes', models.TextField()),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('doctors_phone_number', models.CharField(blank=True, max_length=15)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
