# Generated by Django 4.0.8 on 2024-10-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_location_school_shift_clockinout_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='attendance.school'),
        ),
    ]
